FROM node:22-alpine AS build

WORKDIR /app

ARG VITE_GOOGLE_CLIENT_ID=""
ARG VITE_API_URL=""
ARG VITE_MICROSOFT_AUTH_ENABLED=""
ARG VITE_MICROSOFT_SPA_CLIENT_ID=""
ARG VITE_MICROSOFT_AUTHORITY=""
ARG VITE_MICROSOFT_API_SCOPE=""
ARG VITE_MICROSOFT_REDIRECT_URI=""
ARG VITE_MICROSOFT_POST_LOGOUT_REDIRECT_URI=""

ENV VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID
ENV VITE_API_URL=$VITE_API_URL
ENV VITE_MICROSOFT_AUTH_ENABLED=$VITE_MICROSOFT_AUTH_ENABLED
ENV VITE_MICROSOFT_SPA_CLIENT_ID=$VITE_MICROSOFT_SPA_CLIENT_ID
ENV VITE_MICROSOFT_AUTHORITY=$VITE_MICROSOFT_AUTHORITY
ENV VITE_MICROSOFT_API_SCOPE=$VITE_MICROSOFT_API_SCOPE
ENV VITE_MICROSOFT_REDIRECT_URI=$VITE_MICROSOFT_REDIRECT_URI
ENV VITE_MICROSOFT_POST_LOGOUT_REDIRECT_URI=$VITE_MICROSOFT_POST_LOGOUT_REDIRECT_URI

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .
RUN pnpm build

FROM nginx:1.27-alpine AS production

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
