apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logsentinel.fullname" . }}-drain-worker
spec:
  replicas: {{ .Values.replicaCount.drainWorker | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "logsentinel.name" . }}-drain-worker
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "logsentinel.name" . }}-drain-worker
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: drain-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            allowPrivilegeEscalation: false
          {{- if .Values.resources.drainWorker }}
          resources:
            {{- toYaml .Values.resources.drainWorker | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "logsentinel.fullname" . }}-config
            - secretRef:
                name: {{ include "logsentinel.fullname" . }}-secret
