apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logsentinel.fullname" . }}-secret
type: Opaque
data:
  JWT_SECRET_KEY: {{ required "secret.jwtSecretKey must be set" .Values.secret.jwtSecretKey | b64enc | quote }}
  POSTGRES_PASSWORD: {{ required "secret.postgresPassword must be set" .Values.secret.postgresPassword | b64enc | quote }}
  ENCRYPTION_KEY: {{ required "secret.encryptionKey must be set" .Values.secret.encryptionKey | b64enc | quote }}
