apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logsentinel.fullname" . }}-secret
type: Opaque
data:
  JWT_SECRET_KEY: {{ .Values.secret.jwtSecretKey | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secret.postgresPassword | b64enc | quote }}
