{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "logsentinel.fullname" . }}
  {{- if .Values.monitoring.serviceMonitor.namespace }}
  namespace: {{ .Values.monitoring.serviceMonitor.namespace }}
  {{- end }}
  labels:
    {{- toYaml .Values.monitoring.serviceMonitor.additionalLabels | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: metrics
  namespaceSelector:
    matchNames: [{{ .Release.Namespace | quote }}]
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      authorization:
        type: Bearer
        credentials:
          name: {{ include "logsentinel.secretName" . }}
          key: METRICS_TOKEN
{{- end }}
